[2024-03-02 12:05:44 +0800] [21842] [INFO] Starting gunicorn 21.2.0
[2024-03-02 12:05:44 +0800] [21842] [INFO] Listening at: http://0.0.0.0:5000 (21842)
[2024-03-02 12:05:44 +0800] [21842] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-03-02 12:05:44 +0800] [21932] [INFO] Booting worker with pid: 21932
[2024-03-02 12:05:45 +0800] [21932] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist/__init__.py", line 4, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
[2024-03-02 12:05:45 +0800] [21932] [INFO] Worker exiting (pid: 21932)
[2024-03-02 12:05:45 +0800] [21842] [ERROR] Worker (pid:21932) exited with code 3
[2024-03-02 12:05:45 +0800] [21842] [ERROR] Shutting down: Master
[2024-03-02 12:05:45 +0800] [21842] [ERROR] Reason: Worker failed to boot.
[2024-03-02 12:05:46 +0800] [22069] [INFO] Starting gunicorn 21.2.0
[2024-03-02 12:05:46 +0800] [22069] [INFO] Listening at: http://0.0.0.0:5000 (22069)
[2024-03-02 12:05:46 +0800] [22069] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-03-02 12:05:46 +0800] [22126] [INFO] Booting worker with pid: 22126
[2024-03-02 12:05:46 +0800] [22126] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist/__init__.py", line 4, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
[2024-03-02 12:05:46 +0800] [22126] [INFO] Worker exiting (pid: 22126)
[2024-03-02 12:05:46 +0800] [22069] [ERROR] Worker (pid:22126) exited with code 3
[2024-03-02 12:05:46 +0800] [22069] [ERROR] Shutting down: Master
[2024-03-02 12:05:46 +0800] [22069] [ERROR] Reason: Worker failed to boot.
[2024-03-02 12:09:04 +0800] [18366] [INFO] Starting gunicorn 21.2.0
[2024-03-02 12:09:04 +0800] [18366] [INFO] Listening at: http://0.0.0.0:5000 (18366)
[2024-03-02 12:09:04 +0800] [18366] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-03-02 12:09:04 +0800] [18423] [INFO] Booting worker with pid: 18423
[2024-03-02 12:09:04 +0800] [18423] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist/__init__.py", line 4, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
[2024-03-02 12:09:04 +0800] [18423] [INFO] Worker exiting (pid: 18423)
[2024-03-02 12:09:04 +0800] [18366] [ERROR] Worker (pid:18423) exited with code 3
[2024-03-02 12:09:04 +0800] [18366] [ERROR] Shutting down: Master
[2024-03-02 12:09:04 +0800] [18366] [ERROR] Reason: Worker failed to boot.
[2024-03-02 12:09:05 +0800] [18471] [INFO] Starting gunicorn 21.2.0
[2024-03-02 12:09:05 +0800] [18471] [INFO] Listening at: http://0.0.0.0:5000 (18471)
[2024-03-02 12:09:05 +0800] [18471] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-03-02 12:09:05 +0800] [18478] [INFO] Booting worker with pid: 18478
[2024-03-02 12:09:05 +0800] [18478] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist_venv/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/happychamber.xyz/watchlist/watchlist/__init__.py", line 4, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
[2024-03-02 12:09:05 +0800] [18478] [INFO] Worker exiting (pid: 18478)
[2024-03-02 12:09:05 +0800] [18471] [ERROR] Worker (pid:18478) exited with code 3
[2024-03-02 12:09:05 +0800] [18471] [ERROR] Shutting down: Master
[2024-03-02 12:09:05 +0800] [18471] [ERROR] Reason: Worker failed to boot.
